# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "redis", "~> 5.0"
gem "rspec", "~> 3.12"

gem "pry", "~> 0.14.2"
