# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "redis", "~> 4.1"
gem "minitest", "~> 5.13"

gem "rspec", "~> 3.9"
