#!/bin/bash

# Watches:
# - The debug server binary
# Runs the feature tests against:
# - "real" Redis (make sure it is running)
# - Redis clone (make sure it is running or run the `watch-server` script)

# Either pass a spec name as the first argument or it will default to watching
# and running all specs.
target="$1"

cargo watch \
  --ignore-nothing \
  -w "$(pwd)/target/debug/redis-clone" \
  -w "$(pwd)/tests/functional/$target" \
  -s "cd $(pwd)/tests/functional" \
  -s "TEST_REAL_REDIS=1 bin/rspec $target" \
  -s "bin/rspec $target"
